---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Media statistic: 
    - Jellyfin:
        href: /movie
        description: Watch movie/tv-series!
        icon: jellyfin
        server: my-docker
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096/movie
            key: {{HOMEPAGE_VAR_JELLY}}
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true        

    - Show/movies release timeline:
        widget:
          type: calendar
          view: agenda
          firstDayInWeek: saturday 
          maxEvents: 7 
          integrations: 
            - type: radarr 
              service_group: Media statistic 
              service_name: Radarr 
              color: orange 
              params:
                unmonitored: true 
            - type: sonarr 
              service_group: Media statistic 
              service_name: Sonarr 
              color: teal 
              params: 
                unmonitored: true 

    - Sonarr:
        icon: sonarr
        href: /sonarr
        widget:
          type: sonarr  
          url: http://sonarr:8989/sonarr
          key: {{HOMEPAGE_VAR_SONARR}}
          enableQueue: false # optional, defaults to false

    - Radarr:
        icon: radarr
        href: /radarr
        widget:
          type: radarr
          url: http://radarr:7878/radarr
          key: {{HOMEPAGE_VAR_RADARR}}
          enableQueue: false # optional, defaults to false                

    - Prowlarr:
        href: http://192.168.0.120:9696/
        description: prowlarr
        icon: prowlarr
        server: my-docker
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            key: {{HOMEPAGE_VAR_PROWLARR}}

    - Transmission:
        href: /transmission
        description: Torrent download client
        icon: https://raw.githubusercontent.com/6c65726f79/Transmissionic/main/public/assets/icon/favicon.png
        widget:
            type: transmission
            url: http://transmission:9091
            username: {{HOMEPAGE_VAR_TRANS_USER}}
            password: {{HOMEPAGE_VAR_TRANS_PASS}}              
        
    - Immich:
        href: http://192.168.0.120:2283/photos
        description: photos and videos
        icon: immich
        widget:
          type: immich
          url: http://immich_proxy:8080/
          key: cscyXD0Qdk7J3m36x5UPoEGK6JpkdHXrOCNidSGnWOE

    - Navidrome:
        href: /navmusic
        description: Songs & music
        icon: navidrome
        widget:
            type: navidrome
            url: http://navidrome:4533/navmusic
            user: saurav
            token: {{HOMEPAGE_VAR_NAVI}} #md5(password + salt)
            salt: randomsalt

- Network & Monitoring:             
    - Server uptime:
        href: https://uptimerobot.com/dashboard
        icon: https://uptimerobot.com/favicon.ico
        description: Nginx uptime with uptime robot api
        widget:
          type: uptimerobot
          fields: ["status", "uptime", "lastDown", "downDuration"]
          url: https://api.uptimerobot.com
          key: {{HOMEPAGE_VAR_UPTIME_ROBOT_API}}

    - Uptime Kuma:
        href: http://192.168.0.120:3001/
        description: track uptime of service
        icon: uptime-kuma
        server: my-docker
        container: uptimekuma
        widget:
            fields: ["down", "uptime", "incident"]
            type: uptimekuma
            url: http://uptimekuma:3001
            slug: public


    - Speed tracker:
        href: http://192.168.0.120:3009/admin
        description: Internet speed log
        icon: http://192.168.0.120:3009/favicon.ico
        server: my-docker
        container: speedtest-tracker
        widget:
            type: speedtest
            fields: ["download", "upload", "ping"]
            url: http://speedtest-tracker

    - Watchtower:
        description: Update container
        icon: watchtower
        server: my-docker
        container: watchtower
        widget:
            type: watchtower
            url: http://watchtower:8080
            key: {{HOMEPAGE_VAR_WATCH}}

    - Traefik:
        href: http://192.168.0.120:8080
        description: Traefik admin
        icon: traefik
        server: my-docker
        container: traefik
        widget:
            type: traefik
            url: http://traefik:8080
            # username: username # optional
            # password: password # optional


- Media:
    - Jellyfin:
        href: /movie
        description: Watch movie/tv-series!
        icon: jellyfin
        server: my-docker
        container: jellyfin


    - Radarr:
        href: /radarr
        description: add movies
        icon: radarr
        server: my-docker
        container: radarr


    - Sonarr:
        href: /sonarr
        description: add tv-series
        icon: sonarr
        server: my-docker
        container: sonarr

    - Prowlarr:
        href: http://192.168.0.120:9696/
        description: prowlarr
        icon: prowlarr
        server: my-docker
        container: prowlarr


    - Transmission:
        href: /transmission
        description: Torrent downloads
        icon: transmission
        server: my-docker
        container: transmission

    - Filebrowser (Public):
        href: /media
        description: Store files
        icon: files
        server: my-docker
        container: filebrowser-media

    - Filebrowser:
        href: /private-media
        description: Store files (other)
        icon: files
        server: my-docker
        container: filebrowser-media-private        

    - Navidrome:
        href: /navidrome
        description: Songs & music
        icon: navidrome
        server: my-docker
        container: navidrome


- Utilities:
    - Pairdrop:
        href: {{HOMEPAGE_VAR_PAIRDROP}}
        description: Share files and text
        icon: https://raw.githubusercontent.com/schlagmichdoch/PairDrop/master/public/images/android-chrome-512x512.png
        server: my-docker
        container: pairdrop

    - Blaze:
        href: http://192.168.0.120:6969/
        description: Share files and text
        icon: https://blaze.vercel.app/assets/images/favicon-32x32.png
        server: my-docker
        container: blaze

    - Homeserver Syncthing:
        href: http://192.168.0.120:8384
        description: Homeserver syncthing
        icon: syncthing
        ping: http://192.168.0.120:8384



    - Chrome:
        href: http://192.168.0.120:7777
        description: Remote chromium
        icon: chrome
        server: my-docker
        container: neko-chromium

    - Couchdb:
        href: http://192.168.0.120:5984/_utils/#/_all_dbs
        description: for local sync
        icon: https://couchdb.apache.org/favicon.ico
        server: my-docker
        container: couchdb


- Network & Docker:
    - Portainer:
        href: https://192.168.0.120:9000
        description: manage docker container
        icon: portainer
        server: my-docker
        container: portainer-ce

    - Traefik:
        href: http://192.168.0.120:8080
        description: Traefik admin
        icon: traefik
        # ping: http://192.168.0.120:8080
        server: my-docker
        container: traefik

    - Uptime Kuma:
        href: http://192.168.0.120:3001/
        description: track uptime of service
        icon: uptime-kuma
        server: my-docker
        container: uptimekuma

    - Speedtest tracker:
        href: http://192.168.0.120:3009/
        description: Internet speed log
        icon: http://192.168.0.120:3009/favicon.ico
        server: my-docker
        container: speedtest-tracker

    - Openspeed:
        href: http://192.168.0.120/speed
        description: Speedtest from client to server
        icon: https://raw.githubusercontent.com/openspeedtest/Speed-Test/main/assets/images/icons/favicon.ico                
        server: my-docker
        container: openspeed

        

    - Netdata:
        href: http://192.168.0.120:19999/
        description: Monitoring server
        icon: netdata
        ping: http://192.168.0.120:19999/

    - Netdata Dashboard:
        href: /readme/dashboard.html
        description: minimal dashboard
        icon: netdata
        ping: http://192.168.0.120:2222/



- Development:
    - Nocodb:
        href: http://192.168.0.120:3333/
        description: No code Database
        icon: nocodb
        server: my-docker
        container: nocodb       

    - Mariadb:
        description: Database
        icon: mariadb
        server: my-docker
        container: personaldb
        
    - Nginx:
        href: /readme
        description: read about this server
        icon: nginx
        server: my-docker
        container: nginx


    - VScode:
        href: http://192.168.0.120:8444/
        description: vscode server (private access)
        icon: vscode
        ping: http://192.168.0.120:8444/

    - Ollama AI:
        href: http://192.168.0.120:5173/
        description: ChatGpt Alternative 
        icon: https://ollama.ai/public/ollama.png
        container: ollama-web-ui
        server: my-docker








