---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Saurav | Homeserver dashboard
target: _blank # Possible options include _blank, _self, and _top
statusSyle: basic

# providers:
#   openweathermap: openweathermapapikey
#   weatherapi: weatherapiapikey

color: gray
disableCollapse: true
# headerStyle: boxedWidgets
headerStyle: clean

background: 
  # image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  # https://tailwindcss.com/docs/
  #blur: sm # sm, "", md, xl
  image: /images/bk.png
  saturate: 50 
  brightness: 50 
  opacity: 50 

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: false
    hideVisitURL: false

fiveColumns: true

layout:
# public services ______________________
  Welcome:
    style: row
    columns: 5
    tab: Public

  Public services:
    style: row
    columns: 5
    tab: Public
    # useEqualHeights: true
    
  Stats:
    style: row
    columns: 5
    tab: Public

# private services ______________________
  Sever stats:
    style: row
    columns: 5
    tab: Private

  Utilities:
    style: columns
    columns: 4
    tab: Private


  Local services:
    style: columns
    columns: 4
    tab: Private

  Downloads:
    tab: Private


  Database:
    style: columns
    columns: 4
    tab: Private

  Other containers:
    tab: Private
